### PR TITLE
Allow discarding messages via transforms

### PR DESCRIPTION
**Pull request by davidburhans**
I need a way to prevent websocket messages from ever making it to Kafka. I'm using this for a scenario where websocket clients are consumer-only.

### CODE REVIEW

**Comment by b** [comment]
Thanks! Could you please make the member private and use an accessor named isDiscard?

**Comment by b** [comment]
...and a writer named setDiscard.

**Comment by davidburhans** [comment]
Thanks for the feedback. isDiscard/setDiscard are implemented in AbstractMessage. I made the "discard" member "protected" to match the visibility of the member "topic."

**Comment by b** [comment]
lgtm

**Pull request merged**
